### ISSUE TITLE
HTML or Json response

### ISSUE THREAD

**Issue by tefkin** [1iveowl/CosmosResourceTokenBroker#3]
The request for a resource token is apparently failing because the response is HTML not JSON and the jsonserilizer expects json. In BrokerClientTransportHandler.cs in line 68  'var result = serializer.Deserialize<ResourcePermissionResponse>(jsonReader);' but the commented out code at line 59 is useful 'var test = await response.Content.ReadAsStringAsync();'. I wonder if Microsoft has changed how a function responds or if Ive set my functions/b2c api up badly?

**Comment by 1iveowl** [comment]
I doubt Microsoft have changed anything as this would break all things relying on it. 

Have you looked at the HTML? I'm guessing that it is an error message of some sort.

**Comment by tefkin** [comment]
I'm thinking its more likely something I've set up badly in the Azure function:

- As you suggested, I've looked at the return test message (thanks for leaving in the debugging line) and the return appears to just be the html azure page that you function is running.
- On this basis I re targeted the function url as per your example to include the/api/broker?code=.
- The error message is now "internal server error". See image below.
- Double checked the azure website and it thinks the function is running.
- Also tried to run the azure function broker locally and the error message is "Network sub system is down"

![image](https://user-images.githubusercontent.com/8539220/80929420-d7d76c00-8d79-11ea-88f8-ce2dd2eb5bca.png)


I know I logged in OK as I can see an auth token. I know the function server is running as I have got not authorized messages. Just not sure how to get a resource token back from the Azure function broker (either local or on the azure cloud)?

I suspect its something to do with my azure function set up:

- Some strange message on azure function about "your app is in read only mode" but I figured this was because I uploaded the function code?
- Function app status is running.

Any ideas on obvious mistakes I'm making?

**Comment by 1iveowl** [comment]
Sorry, but difficult to tell from this alone.

Have you gotten any further with this?

**Comment by tefkin** [comment]
Agreed. Actually I've made a bit of progress:

Issue one solved: there is some nuget incompatability with Azure around token management. The solution is to roll back nuget. Details [here.](https://github.com/Azure/azure-functions-host/issues/5756)
When I roll back, I can hit the azure function from browser.


Issue two WIP: Now i'm getting this 'network subsystem down' error when I try to hit the azure function from inside the app. Apparently this an out of date xamarin known issue. But I haven't proved this to myself yet. Link [here](https://forums.xamarin.com/discussion/171413/network-subsystem-is-down-but-it-works-on-browser).

**Comment by tefkin** [comment]
All the way through. Thanks again.

A few takeaways for other users:

- I got the function url confused. I should have been using the full function url with the code element and not just the high level azure shortcut.
- The network subsystem error was just me still pointing at the local version of the broker in my config. Worked fine once I was back on Azure version of the broker.
- Main remaining issues was different nuget versions not working together. Upgraded Microsoft.azure.cosmos from 3.6 to 3.8 and that fixed the last batch of errors related to Microsoft.Azure.Documents.StoreClientFactory not being found.

**Comment by tefkin** [comment]
See May 10
